# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build source image
        command: |
          docker build -t $CIRCLE_PROJECT_REPONAME:$(echo $CIRCLE_SHA1 | cut -c -7) .
  push:
    docker:
      - image: circleci/golang:1.12
    steps:
    - setup_remote_docker
    - run: 
        name: DockerHub Login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run:
        name: Push to registry
        command: |
          docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:latest
          docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$(echo $CIRCLE_SHA1 | cut -c -7)

workflows:
  version: 2
  create-images:
    jobs:
      - build
      - push:
          requires:
          - build
          filters:
            branches:
              only: 
                - master